Output assets/demo.gif

Require echo

Set Shell "zsh"
Set WindowBar Colorful
Set Theme "Catppuccin Frappe"
Set FontSize 32
Set FontFamily "JetBrainsMonoNL Nerd Font"
Set Width 1200
Set Height 600

Type "cargo run" Sleep 500ms  Enter
Sleep 1s

Set TypingSpeed 250ms
Type "asse"
Enter

Set TypingSpeed 250ms
Type "test_file.py"
Ctrl+N

Ctrl+J
Ctrl+J

Set TypingSpeed 250ms
Type "test"

Ctrl+D
Sleep 1s
Ctrl+y

Sleep 5s
